### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [Rafaustino/EDL#1]
Obrigado.
- Comentários:
  - Mostrar um exemplo de código fonte em que C++ se destaca das demais linguagens.

**Comment by Rafaustino** [comment]
É pra colocar um código fonte, professor?

**Comment by fsantanna** [comment]
Sim. Você já colocou alguns exemplos de código fonte no artigo.
Queria que você colocasse mais um, algum que destacasse o estilo de C++ em comparação com outras linguagens (justificando).

**Comment by Rafaustino** [comment]
Coloquei mais um ontem a noite, professor. Explicando sobre herança múltipla, que é uma das características de C++ e que faz com que C++ se destaque destaque das demais linguagens nesse ponto. 

Enviado do meu iPhone

**Comment by fsantanna** [comment]
obrigado.
